# Generated by Django 3.2.9 on 2021-11-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.CASCADE, to='instagram.post'),
        ),
    ]
